#docker-compose.yml
version: '3.3'
services:

  maboss-server:
    build:
      context: ./
      dockerfile: containers/docker/Dockerfile

    image: maboss
    container_name: maboss
    ports:
      - "7777:7777"
      - "7778:7778"
      - "7779:7779"
      - "7780:7780"
      - "7781:7781"
    restart: unless-stopped

