[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy==1.13.3; python_version<'3.5'",
    "oldest-supported-numpy; python_version>='3.5'",
]

build-backend = "setuptools.build_meta"

# Install libSBML with all packages
[tool.cibuildwheel.linux]
before-all = [
    "yum install wget libxml2-devel -y",
    "GCC=gcc CXX=g++ INSTALL_PATH=/usr/ BUILD_PATH=/tmp/ LIBXML_LIBDIR=/usr/lib64/libxml2.so LIBXML_INCLUDEDIR=/usr/include/libxml2 bash scripts/build_libsbml.sh",
    "BUILD_PATH=/tmp/ bash scripts/install_libsbml.sh"
]
skip = [
    "*-manylinux_i686",
    "*-musllinux_*"
]

[tool.cibuildwheel.macos]
before-all = [
    "brew install libxml2",
    "GCC=clang CXX=clang++ INSTALL_PATH=/usr/local/ BUILD_PATH=/tmp/ LIBXML_LIBDIR=/usr/local/opt/libxml2/lib/libxml2.dylib LIBXML_INCLUDEDIR=/usr/local/opt/libxml2/include/libxml2/ bash scripts/build_libsbml.sh",
    "BUILD_PATH=/tmp/ bash scripts/install_libsbml.sh",
    "cp /usr/local/lib/libsbml* ."
]
archs = ["x86_64", "arm64"]
skip = ["pp*"]

[tool.cibuildwheel]
test-command = [
  "cd {project}/engine/tests",
  "python -m unittest test",
  "python -m unittest test_128n",
]