package:
  name: maboss
  version: "2.2.0"

source:
  git_url: https://github.com/maboss-bkmc/MaBoSS-env-2.0.git

build:
  number: 0

requirements:
  build:
    - gcc
    - flex
    - bison
    - make
  run:
    - libgcc-ng
    - libstdcxx-ng

about:
  home:  https://maboss.curie.fr

