{% set name = "MaBoSS" %}
{% set version = "2.3.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../..
    
build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make
    - libsbml-plus-packages-namespace
    - libxml2
        
  host:
    - libsbml-plus-packages-namespace
    - libxml2
    
  run:
    - libsbml-plus-packages-namespace
    - libxml2
      
about:
  home:  https://maboss.curie.fr

