{% set name = "MaBoSS" %}
{% set version = "2.3.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/sysbio-curie/MaBoSS-env-2.0.git
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make

about:
  home:  https://maboss.curie.fr

