{% set name = "cMaBoSS" %}
{% set version = "1.0.0b26" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../..


build:
  {% if CUSTOM_BUILD_NUMBER is defined %}
  number: {{ CUSTOM_BUILD_NUMBER }}
  {% else %}
  number: 0
  {% endif %}
  script_env:
    - SBML_COMPAT
    - SEDML_COMPAT

requirements:
  build:
    - setuptools
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - flex  # [not win]
    - bison  # [not win]
    - winflexbison  # [win]
    - make
    - python {{ python }}
    - numpy
    - libsbml-plus-packages
    
  host: 
    - setuptools
    - python {{ python }}
    - numpy
    - libsbml-plus-packages
  
  run: 
    - python {{ python }}
    - libsbml-plus-packages

test:
  requires:
    - numpy
    - pandas
  
about:
  home:  https://maboss.curie.fr

