{% set name = "cMaBoSS" %}
{% set version = "1.0.0b0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/sysbio-curie/MaBoSS-env-2.0.git
  git_rev: release

build:
  number: 0
  string: py{{CONDA_PY}}

requirements:
  build:
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make
    - python {{ python }}

  run: 
    - python {{ python }}

about:
  home:  https://maboss.curie.fr

