{% set name = "cMaBoSS" %}
{% set version = "1.0.0b17" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../..


build:
  {% if CUSTOM_BUILD_NUMBER is defined %}
    number: {{ CUSTOM_BUILD_NUMBER }}
  {% else %}
    number: 0
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - libsbml-plus-packages
    - libxml2
    
  host: 
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - libsbml-plus-packages
    - libxml2
  
  run: 
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - libsbml-plus-packages
    - libxml2

about:
  home:  https://maboss.curie.fr

