{% set name = "cMaBoSS" %}
{% set version = "1.0.0b27" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../..


build:
  {% if CUSTOM_BUILD_NUMBER is defined %}
  number: {{ CUSTOM_BUILD_NUMBER }}
  {% else %}
  number: 0
  {% endif %}
  script_env:
    - SBML_COMPAT
    - SEDML_COMPAT

requirements:
  build:
    - setuptools
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - flex  # [not win]
    - bison  # [not win]
    - winflexbison  # [win]
    - make  # [not win]
    - cmake
    - ninja
    - python {{ python }}
    - numpy
    - {{ LIBSBML_PACKAGE }}
    - python-gil  # [py>=313]

  host: 
    - python {{ python }}
    - pip
    - scikit-build-core
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x') }}
    - {{ LIBSBML_PACKAGE }}
    - python-gil  # [py>=313]
  
  run: 
    - python {{ python }}
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x') }}
    - {{ LIBSBML_PACKAGE }}
    - python-gil  # [py>=313]
test:
  requires:
    - python {{ python }}
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x') }}
    - pandas
    - python-gil  # [py>=313]

about:
  home:  https://maboss.curie.fr

