name: cMaBoSS MacOS

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  cmaboss_macos:
    name: cMaBoSS
    runs-on: macos-13
    env:
      CC: clang
      CXX: clang++
      INSTALL_PATH: /usr/local/
      BUILD_PATH: /tmp/
      LIBXML_LIBDIR: /usr/local/opt/libxml2/lib/libxml2.dylib
      LIBXML_INCLUDEDIR: /usr/local/opt/libxml2/include/libxml2/
      MACOSX_DEPLOYMENT_TARGET: 13.0
      SBML_COMPAT: 1
    steps:
    - uses: actions/checkout@v4 

    - name: Install dependencies
      run: |
        brew install flex bison python3 cmake libxml2 ninja
        python3 -m pip install --upgrade pip
        pip3 install numpy wheel delocate pandas scikit-build-core

    - name: Set cmake version variable
      run: |
        echo "CMAKE_VERSION=$(cmake --version | head -n 1)" >> $GITHUB_ENV

    - name: Cache compiled libSBML
      id: cache-libsbml-clang
      uses: actions/cache@v4
      with:
        path: /tmp/libsbml-5.20.5
        key: ${{ runner.os }}-${{ env.CMAKE_VERSION }}-libSBML-5.20.5-clang++-namespace

    - name: Compiling libSBML
      if: steps.cache-libsbml-clang.outputs.cache-hit != 'true'
      run: bash scripts/build_libsbml.sh
    
    - name: Install libSBML
      run: sudo bash scripts/install_libsbml.sh
            
    - name: Build cMaBoSS
      env: 
        FLEX_ROOT: /usr/local/opt/flex/bin
        BISON_ROOT: /usr/local/opt/bison/bin
      run: |
        cd engine/python
        python3 -m pip wheel -w wheelhouse .
        delocate-wheel -w fixed_wheels -v `ls wheelhouse/cmaboss*.whl`
        pip3 install `ls fixed_wheels/cmaboss*.whl` 
        
    - name: Test cMaBoSS
      env: 
        FLEX_ROOT: /usr/local/opt/flex/bin
        BISON_ROOT: /usr/local/opt/bison/bin
      run: |
        bash scripts/run_cmaboss_tests.sh
  
  build_wheels_macos:
    name: Build MacOS wheels
    runs-on: macos-13
    needs: cmaboss_macos
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Install dependencies
        run: |
          brew install flex bison 
        
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel numpy twine

      - name: Build wheels
        env: 
          SBML_COMPAT: 1
          MACOSX_DEPLOYMENT_TARGET: 13.0
          CIBW_ARCHS: x86_64
          CIBW_BEFORE_ALL: >
            brew install libxml2 &&
            CC=clang CXX=clang++ INSTALL_PATH=/usr/local/ BUILD_PATH=/tmp/ \
              LIBXML_LIBDIR=/usr/local/opt/libxml2/lib/libxml2.dylib \
              LIBXML_INCLUDEDIR=/usr/local/opt/libxml2/include/libxml2/ \
              CPU_COUNT=4 bash scripts/build_libsbml.sh && 
            BUILD_PATH=/tmp/ bash scripts/install_libsbml.sh
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            DYLD_LIBRARY_PATH=/usr/local/lib/ delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
          CIBW_SKIP: cp36-* cp37-* pp*
          CIBW_TEST_REQUIRES: pandas
          CIBW_TEST_COMMAND: >
            cd {project}/engine/tests &&
            python -m unittest test.py &&
            python -m unittest test_128n.py
          FLEX_ROOT: /usr/local/opt/flex/bin
          BISON_ROOT: /usr/local/opt/bison/bin
        run: |
          python -m cibuildwheel --output-dir wheelhouse engine/python

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: wheelhouse/*.whl
          
      - name: Upload cMaBoSS to test Pypi
        if: github.repository == 'vincent-noel/MaBoSS' && github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          python -m twine upload --repository testpypi --skip-existing wheelhouse/cmaboss*
          
      - name: Upload cMaBoSS to Pypi
        if: github.repository == 'sysbio-curie/MaBoSS' && github.event_name == 'release'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload --skip-existing wheelhouse/cmaboss*
          
  build_wheels_macos_arm64:
    name: Build MacOS wheels (M1)
    runs-on: macos-14
    needs: cmaboss_macos
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          brew install flex bison 
      
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel numpy twine

      - name: Build wheels
        env:
          SBML_COMPAT: 1
          MACOSX_DEPLOYMENT_TARGET: 14.0 
          CIBW_ARCHS: arm64
          CIBW_BEFORE_ALL: >
            brew install libxml2 &&
            CC=clang CXX=clang++ INSTALL_PATH=/usr/local/ BUILD_PATH=/tmp/ \
              LIBXML_LIBDIR=/opt/homebrew/opt/libxml2/lib/libxml2.dylib \
              LIBXML_INCLUDEDIR=/opt/homebrew/opt/libxml2/include/ \
              CPU_COUNT=3 bash scripts/build_libsbml.sh && 
            BUILD_PATH=/tmp/ sudo bash scripts/install_libsbml.sh
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            DYLD_LIBRARY_PATH=/usr/local/lib/ delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
          CIBW_SKIP: pp*
          CIBW_TEST_REQUIRES: pandas
          CIBW_TEST_COMMAND: >
            cd {project}/engine/tests &&
            python -m unittest test.py &&
            python -m unittest test_128n.py
          FLEX_ROOT: /opt/homebrew/opt/flex/bin
          BISON_ROOT: /opt/homebrew/opt/bison/bin
        run: |
          python -m cibuildwheel --output-dir wheelhouse engine/python

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-arm64
          path: wheelhouse/*.whl
          
      - name: Upload cMaBoSS to test Pypi
        if: github.repository == 'sysbio-curie/MaBoSS' && github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          python -m twine upload --repository testpypi --skip-existing wheelhouse/cmaboss*
          
      - name: Upload cMaBoSS to Pypi
        if: github.repository == 'sysbio-curie/MaBoSS' && github.event_name == 'release'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload --skip-existing wheelhouse/cmaboss*
    

  conda_cmaboss_macosx_condaforge:
    name: cMaBoSS conda package (${{matrix.repo.name}}, python ${{matrix.version.python}}, numpy ${{matrix.version.numpy}})
    needs: cmaboss_macos

    strategy:
      fail-fast: false
      matrix:
        repo: [
          {name: defaults, deployment_target: "10.9", libsbml: libsbml-plus-packages, libsbml_source: colomoto, build_number: 0},
          {name: conda-forge, deployment_target: "10.13", libsbml: libsbml, libsbml_source: conda-forge, build_number: 1}
        ]
        version: [
          {python: "3.8", numpy: "1.24"}, 
          {python: "3.9", numpy: "2.0"}, 
          {python: "3.10", numpy: "2.0"}, 
          {python: "3.11", numpy: "2.0"}, 
          {python: "3.12", numpy: "2.0"}, 
          {python: "3.13", numpy: "2.1"}
        ]
    runs-on: macos-13

    defaults:
      run:
        shell: sh -l {0}
            
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        conda-remove-defaults: "true"
        channels: ${{ matrix.repo.name }}
        python-version: 3.12
        use-mamba: true
        
    - name: Install conda-build
      run: |
        conda install conda-build conda-verify anaconda-client
    
    - name: Installing MacOSX${{ matrix.repo.deployment_target }} SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX${{ matrix.repo.deployment_target }}.sdk.tar.xz
        sudo tar xf MacOSX${{ matrix.repo.deployment_target }}.sdk.tar.xz -C /opt
        echo "conda_build:" > ~/.condarc
        echo "  config_file: ~/.conda/conda_build_config.yaml" >> ~/.condarc
        echo "CONDA_BUILD_SYSROOT:" > ~/.conda/conda_build_config.yaml
        echo "  - /opt/MacOSX${{ matrix.repo.deployment_target }}.sdk        # [osx]" >> ~/.conda/conda_build_config.yaml
      
    - name: Build cMaBoSS Anaconda package
      env:
        MACOSX_DEPLOYMENT_TARGET: ${{ matrix.repo.deployment_target }}
        SBML_COMPAT: 1
        CUSTOM_BUILD_NUMBER: ${{ matrix.repo.build_number }}
        LIBSBML_PACKAGE: ${{ matrix.repo.libsbml }}
      run: |
        conda build -c ${{ matrix.repo.libsbml_source }} --variants "{\"python\": [\"${{ matrix.version.python }}\"], \"numpy\": [\"${{ matrix.version.numpy }}\"]}" conda/cmaboss;
    
    - name: Upload MaBoSS to Anaconda cloud on vincent-noel
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel $CONDA/envs/test/conda-bld/osx-64/*.conda --force;
    
    - name: Upload MaBoSS to Anaconda cloud on colomoto
      if: github.repository == 'sysbio-curie/MaBoSS' && github.event_name == 'release'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u colomoto $CONDA/envs/test/conda-bld/osx-64/*.conda --force;
  
        
  conda_cmaboss_macosx_M1_defaults:
    name: cMaBoSS conda arm64 package (${{matrix.repo.name}}, python ${{matrix.version.python}}, numpy ${{matrix.version.numpy}})
    needs: cmaboss_macos

    strategy:
      fail-fast: false
      matrix:
        repo: [
          {name: defaults, deployment_target: "11.1", libsbml: libsbml-plus-packages, libsbml_source: colomoto, build_number: 0},
          {name: conda-forge, deployment_target: "11.0", libsbml: libsbml, libsbml_source: conda-forge, build_number: 1}
        ]
        version: [
          {python: "3.8", numpy: "1.24"}, 
          {python: "3.9", numpy: "2.0"}, 
          {python: "3.10", numpy: "2.0"}, 
          {python: "3.11", numpy: "2.0"}, 
          {python: "3.12", numpy: "2.0"}, 
          {python: "3.13", numpy: "2.1"}
          ]
    runs-on: macos-14

    defaults:
      run:
        shell: sh -l {0}
            
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        conda-remove-defaults: "true"
        channels: ${{ matrix.repo.name }}
        python-version: 3.12
        use-mamba: true
        
    - name: Install conda-build
      run: |
        conda install conda-build conda-verify anaconda-client
    
    - name: Installing MacOSX${{ matrix.repo.deployment_target }} SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX${{ matrix.repo.deployment_target }}.sdk.tar.xz
        sudo tar xf MacOSX${{ matrix.repo.deployment_target }}.sdk.tar.xz -C /opt
        echo "conda_build:" > ~/.condarc
        echo "  config_file: ~/.conda/conda_build_config.yaml" >> ~/.condarc
        echo "CONDA_BUILD_SYSROOT:" > ~/.conda/conda_build_config.yaml
        echo "  - /opt/MacOSX${{ matrix.repo.deployment_target }}.sdk        # [osx]" >> ~/.conda/conda_build_config.yaml
      
    - name: Build cMaBoSS Anaconda package
      env:
        MACOSX_DEPLOYMENT_TARGET: ${{ matrix.repo.deployment_target }}
        SBML_COMPAT: 1
        CUSTOM_BUILD_NUMBER: ${{ matrix.repo.build_number }}
        LIBSBML_PACKAGE: ${{ matrix.repo.libsbml }}
      run: |
        conda build -c ${{ matrix.repo.libsbml_source }} --variants "{\"python\": [\"${{ matrix.version.python }}\"], \"numpy\": [\"${{ matrix.version.numpy }}\"]}" conda/cmaboss;
        
    - name: Upload MaBoSS to Anaconda cloud on vincent-noel
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel $CONDA/envs/test/conda-bld/osx-arm64/*.conda --force;
    
    - name: Upload MaBoSS to Anaconda cloud on colomoto
      if: github.repository == 'sysbio-curie/MaBoSS' && github.event_name == 'release'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u colomoto $CONDA/envs/test/conda-bld/osx-arm64/*.conda --force;
