name: Tests MacOSX

on:
  push:
  pull_request:
  release:
    types: [created]
    
jobs:

###################################################################################################
# MaBoSS                                                                                          #
###################################################################################################
  maboss:
    name: MaBoSS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run : |
        brew install flex bison gcc@10 libxml2 cmake
        pip install numpy
        pwd
        
    - name: Cache compiled libSBML
      id: cache-libsbml-gcc
      uses: actions/cache@v2
      with:
        path: /Users/runner/work/MaBoSS-env-2.0/MaBoSS-env-2.0/libSBML-5.19.0-Source
        key: ${{ runner.os }}-libSBML-5.19-g++

    - name: Compiling libSBML
      if: steps.cache-libsbml-gcc.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/sbml/files/libsbml/5.19.0/stable/libSBML-5.19.0-core-plus-packages-src.tar.gz
        tar -zxf libSBML-5.19.0-core-plus-packages-src.tar.gz
        cd libSBML-5.19.0-Source
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
        -DCMAKE_CXX_COMPILER=g++-10 \
        -DCMAKE_C_COMPILER=gcc-10 \
        -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
        -DWITH_SWIG=OFF \
        -DLIBXML_LIBRARY=/usr/local/opt/libxml2/lib \
        -DLIBXML_INCLUDE_DIR=/usr/local/opt/libxml2/include/libxml2 \
        -DENABLE_COMP=ON \
        -DENABLE_FBC=ON \
        -DENABLE_GROUPS=ON \
        -DENABLE_LAYOUT=ON \
        -DENABLE_MULTI=ON \
        -DENABLE_QUAL=ON \
        -DENABLE_RENDER=ON \
        -DENABLE_DISTRIB=ON \
        ..
        make
        cd ../..
        
    - name: Install libSBML
      run: |
        cd libSBML-5.19.0-Source/build
        sudo make install

    - name: Build MaBoSS
      run: |
        cd engine/src
        make clean
        export CXXFLAGS="${CXXFLAGS} -I/usr/local/include -I/usr/local/include/libxml2"
        export LDFLAGS="${LDFLAGS} -L/usr/local/lib -lxml2"
        make CXX=g++-10 install SBML_COMPAT=1
        make CXX=g++-10 MAXNODES=128 install SBML_COMPAT=1
        
    - name: Test MaBoSS
      run: |
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-user_func.sh"
        
  maboss_llvm:
    name: MaBoSS (clang)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run : |
        brew install flex bison libxml2 cmake
        pip install numpy
    
    - name: Cache compiled libSBML
      id: cache-libsbml-clang
      uses: actions/cache@v2
      with:
        path: /Users/runner/work/MaBoSS-env-2.0/MaBoSS-env-2.0/libSBML-5.19.0-Source
        key: ${{ runner.os }}-libSBML-5.19-clang++

    - name: Compiling libSBML
      if: steps.cache-libsbml-clang.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/sbml/files/libsbml/5.19.0/stable/libSBML-5.19.0-core-plus-packages-src.tar.gz
        tar -zxf libSBML-5.19.0-core-plus-packages-src.tar.gz
        cd libSBML-5.19.0-Source
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
        -DWITH_SWIG=OFF \
        -DLIBXML_LIBRARY=/usr/local/opt/libxml2/lib \
        -DLIBXML_INCLUDE_DIR=/usr/local/opt/libxml2/include/libxml2 \
        -DENABLE_COMP=ON \
        -DENABLE_FBC=ON \
        -DENABLE_GROUPS=ON \
        -DENABLE_LAYOUT=ON \
        -DENABLE_MULTI=ON \
        -DENABLE_QUAL=ON \
        -DENABLE_RENDER=ON \
        -DENABLE_DISTRIB=ON \
        ..
        make
        cd ../..
    
    - name: Install libSBML
      run: |
        cd libSBML-5.19.0-Source/build
        sudo make install

    - name: Build MaBoSS
      run: |
        cd engine/src
        make clean
        g++ --version
        make CXX=g++ install SBML_COMPAT=1
        make CXX=g++ MAXNODES=128 install SBML_COMPAT=1
        
    - name: Test MaBoSS
      run: |
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-user_func.sh"
  
  conda_maboss:
    name: Build Conda MaBoSS package
    runs-on: macos-latest
    needs: maboss
  
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Installing conda-build      
      run: conda install conda-build anaconda-client

    - name: Downgrading XCode to 11.7
      run: |
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
        brew reinstall llvm    
    
    - name: Build MaBoSS Anaconda package
      run: |
        conda build -c vincent-noel conda/maboss
              
    - name: Upload MaBoSS to Anaconda cloud
      if: github.repository == 'vincent-noel/MaBoSS-env-2.0'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 
  maboss_conda_test:
    name: MaBoSS Anaconda package test
    runs-on: macos-latest
    needs: conda_maboss
    
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    
    - name: Install package
      run: conda install -c vincent-noel maboss
      
    - name: Test package
      run: |
        pip install numpy
        export MABOSS=/usr/local/miniconda/bin/MaBoSS
        export MABOSS_128n=/usr/local/miniconda/bin/MaBoSS_128n
        export MABOSS_CLIENT=/usr/local/miniconda/bin/MaBoSS-client
        export MABOSS_SERVER=/usr/local/miniconda/bin/MaBoSS-server
        export MABOSS_SERVER_128n=/usr/local/miniconda/bin/MaBoSS_128n-server
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
        
###################################################################################################
# cMaBoSS                                                                                         #
###################################################################################################                        
  cmaboss:
    name: cMaBoSS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Install dependencies
      run: |
        brew install flex bison gcc@10 python3 libxml2 cmake
        pip3 install numpy
        
    - name: Cache compiled libSBML
      id: cache-libsbml-clang
      uses: actions/cache@v2
      with:
        path: /Users/runner/work/MaBoSS-env-2.0/MaBoSS-env-2.0/libSBML-5.19.0-Source
        key: ${{ runner.os }}-libSBML-5.19-clang++

    - name: Compiling libSBML
      if: steps.cache-libsbml-clang.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/sbml/files/libsbml/5.19.0/stable/libSBML-5.19.0-core-plus-packages-src.tar.gz
        tar -zxf libSBML-5.19.0-core-plus-packages-src.tar.gz
        cd libSBML-5.19.0-Source
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
        -DWITH_SWIG=OFF \
        -DLIBXML_LIBRARY=/usr/local/opt/libxml2/lib \
        -DLIBXML_INCLUDE_DIR=/usr/local/opt/libxml2/include/libxml2 \
        -DENABLE_COMP=ON \
        -DENABLE_FBC=ON \
        -DENABLE_GROUPS=ON \
        -DENABLE_LAYOUT=ON \
        -DENABLE_MULTI=ON \
        -DENABLE_QUAL=ON \
        -DENABLE_RENDER=ON \
        -DENABLE_DISTRIB=ON \
        .. 
        make 
        cd ../..
    
    - name: Install libSBML
      run: |
        cd libSBML-5.19.0-Source/build
        sudo make install
    
    - name: Build cMaBoSS
      run: |
        cd engine/src
        make
        cd ../python
        cp -r ../src .
        python3 setup.py build_ext --inplace
        cd ../..
    
    - name: Test cMaBoSS
      run: |
        cd engine/python
        python3 -m unittest test
        python3 -m unittest test_128n
  
  conda_cmaboss:
    name: cMaBoSS Conda package
    runs-on: macos-latest
    needs: cmaboss

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: conda install conda-build anaconda-client
      
    - name: Downgrading XCode to 11.7
      run: |
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
        brew reinstall llvm    
    
    - name: Build cMaBoSS Anaconda package
      run: |
        conda build -c vincent-noel conda/cmaboss;   
        
    - name: Upload cMaBoSS to Anaconda cloud
      if: github.repository == 'vincent-noel/MaBoSS-env-2.0'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 
  cmaboss_conda_test:
    name: cMaBoSS Anaconda package test
    runs-on: macos-latest
    needs: conda_cmaboss
    
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    
    - name: Install package
      run: conda install -c vincent-noel cmaboss
      
    - name: Test package
      run: python -c "import cmaboss"
            
  cmaboss_pypi:
    name: cMaBoSS PyPi package
    runs-on: macos-latest

    strategy:
      matrix:
        python:
          - 3.5.10
          - 3.6.12
          - 3.7.9
          - 3.8.6
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python env
      uses: gabrielfalcao/pyenv-action@v7
      with:
        default: "${{ matrix.python }}"
        command: |
          pip install -U pip  # upgrade pip after installing python
          
    - name: Install python dependencies
      run: pip install twine wheel numpy

    - name: Install libSBML
      run: |
        brew install flex bison gcc@10 python3 libxml2 cmake
        pip3 install numpy delocate
    
    - name: Cache compiled libSBML
      id: cache-libsbml-clang
      uses: actions/cache@v2
      with:
        path: /Users/runner/work/MaBoSS-env-2.0/MaBoSS-env-2.0/libSBML-5.19.0-Source
        key: ${{ runner.os }}-libSBML-5.19-clang++

    - name: Compiling libSBML
      if: steps.cache-libsbml-clang.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/sbml/files/libsbml/5.19.0/stable/libSBML-5.19.0-core-plus-packages-src.tar.gz
        tar -zxf libSBML-5.19.0-core-plus-packages-src.tar.gz
        cd libSBML-5.19.0-Source
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
        -DWITH_SWIG=OFF \
        -DLIBXML_LIBRARY=/usr/local/opt/libxml2/lib \
        -DLIBXML_INCLUDE_DIR=/usr/local/opt/libxml2/include/libxml2 \
        -DENABLE_COMP=ON \
        -DENABLE_FBC=ON \
        -DENABLE_GROUPS=ON \
        -DENABLE_LAYOUT=ON \
        -DENABLE_MULTI=ON \
        -DENABLE_QUAL=ON \
        -DENABLE_RENDER=ON \
        -DENABLE_DISTRIB=ON \
        .. 
        make 
        cd ../..
        
    - name: Install libSBML
      run: |
        cd libSBML-5.19.0-Source/build
        sudo make install
    
    - name: Compile MaBoSS
      run: |
        cd engine/src; make
        cd ../python; cp -r ../src cmaboss/
        cd ../..
    
    - name: Cache wheel
      uses: actions/cache@v2
      with:
        path: /Users/runner/work/MaBoSS-env-2.0/MaBoSS-env-2.0/engine/python/fixed_wheels/*
        key: ${{ runner.os }}-wheel-${{ matrix.python }}-${{ github.run_id }}

    - name: Build cMaBoSS
      run: |
        cd engine/python
        pip wheel -w wheelhouse .
        
    - name: Fix wheel dependencies
      run: |
        cd engine/python
        cp /usr/local/lib/libsbml*.dylib .
        delocate-wheel -w fixed_wheels -v `ls wheelhouse/cmaboss*.whl`
        ls -al fixed_wheels

  cmaboss_wheel_test:
    name: cMaBoSS Wheel test
    runs-on: macos-latest
    needs: cmaboss_pypi
    strategy:
      matrix:
        python:
          - 3.5.10
          - 3.6.12
          - 3.7.9
          - 3.8.6
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python env
      uses: gabrielfalcao/pyenv-action@v7
      with:
        default: "${{ matrix.python }}"
        command: |
          pip install -U pip  # upgrade pip after installing python
          
    - name: Install python dependencies
      run: pip install twine wheel numpy pandas

    - name: Cache wheel
      uses: actions/cache@v2
      with:
        path: /Users/runner/work/MaBoSS-env-2.0/MaBoSS-env-2.0/engine/python/fixed_wheels/*
        key: ${{ runner.os }}-wheel-${{ matrix.python }}-${{ github.run_id }}

    - name: Install wheel
      run: |
        cd engine/python
        ls -al fixed_wheels
        unzip -l fixed_wheels/*.whl
        pip install -f fixed_wheels --no-index cmaboss
        
    - name: Test wheel
      run: |
        cd engine/python
        rm -fr cmaboss cmaboss_128n cmaboss_256n cmaboss_512n cmaboss_1024n
        python -m unittest test
        python -m unittest test_128n
                
    - name: Upload cMaBoSS to Pypi
      if: github.event_name == 'release' && github.event.action == 'created' && github.repository == 'sysbio-curie/MaBoSS-env-2.0'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine upload --skip-existing fixed_wheels/cmaboss*